### ISSUE TITLE
does not compile

### ISSUE THREAD

**Issue by catwell** [robn/salada#1]
Probably because of [last commit](https://github.com/robn/salada/commit/eeed316d8b0a18077a5a6957ff34d00560683335), I get:

```
$ cargo run
   Compiling salada v0.0.5 (file:///home/catwell/tmp/jmap/salada)
src/db.rs:9:5: 9:40 error: unresolved import `jmap::calendar_event::CalendarEvent`. Could not find `calendar_event` in `jmap`
src/db.rs:9 use jmap::calendar_event::CalendarEvent;
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/db.rs:11:5: 11:38 error: unresolved import `jmap::contact_group::ContactGroup`. Could not find `contact_group` in `jmap`
src/db.rs:11 use jmap::contact_group::ContactGroup;
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to 2 previous errors
Could not compile `salada`.
```

This is probably because jmap-rs is not up to date in the package manager. The previous commit builds fine.

**Comment by robn** [comment]
Yeah, if you're going to use git master, then you have to update Cargo.toml to use git master instead of the released version from crates.io. I don't have a good way to manage this yet.
